### ISSUE TITLE
Keoma#1_ProtectionCulturalHeritage

### ISSUE THREAD

**Issue by uinfobrera** [polifonia-project/stories#4]
## ID of the story
Keoma#1_ProtectionCulturalHeritage
## WP
WP1
## Pilots
BELLS
## Priority
 avoid the alteration of the characteristics of the cell as a component of the production of the bells sound
## Persona
Keoma
## Goal
- sound practices
- spectrum analysis program
## Scenario
Keoma has to draw up a renovation plan for a bell tower damaged by the earthquake and wants to know what kind of interventions to implement on the wall structure. He needs to to avoid the alteration of the characteristics of the cell as a component of the production of the bells sound. Keoma therefore needs to know what kind of sound practices are performed in that bell tower. Keoma needs to know if sound practices are currently practiced and how often, and if those sound techniques involve humans and, if so, how many people are generally employed in the performance. Keoma must also understand if there are significant differences between the sound performed manually and the electrified one, in order to develop indications related to the impact on the soundscape in both cases. Keoma also needs to know if there are documents that proof to the diffusion of this sound in surrounding space back in time, in order to document any prescriptions that he will elaborate on a historical basis.
## Competency questions
CQ1:  Where is the Bell Tower?
CQ2:  What kind of repertoire is traditionally performed in that specific location?
CQ3:  What is the dating that accompanies this repertoire?
CQ4:  Is it a repertoire performed in the contemporary world?
CQ4:  Is it a repertoire in that place currently performed by hand or by electric means?
CQ5:  How many people are generally employed for the performance of these sound practices?
CQ6:  Are there significant variations in the frequencies between the manually produced sound and the electric sound, such as to have repercussions on the soundscape?
CQ7:  Are there historical evidences of the presence of that sound in the surrounding area?

**Comment by enridaga** [comment]
This is brilliant! I suggest we add it to the scenarios in the repository. `Kaoma: Restorer`?

**Comment by Valentina10** [comment]
The story has been added to the repository, in [this folder](https://github.com/polifonia-project/stories/tree/main/Keoma:%20Architect)
