### ISSUE TITLE
Patrizia#1_DemoEthnoAnthropologistOfficer

### ISSUE THREAD

**Issue by uinfobrera** [polifonia-project/stories#5]
## ID of the story
Patrizia#1_DemoEthnoAnthropologistOfficer

## WP
WP1
## Priority
sound practices conducted by collective social actors 
## Persona
Patrizia is a Demo-Ethno-anthropologist Officer of the Ministry and is responsible for the safeguarding of the Intangible Heritage pursuant to the 2003 Unesco Convention.

## Goal
- bell towers
- groups practices

## Scenario
Patrizia must propose safeguarding actions on some sound practices located in the territory of the Region starting from specific locations. She needs to know if the bells of some bell towers are involved in sound practices conducted by collective social actors who recognize those practices as constitutive trait of their collective identity. Patrizia starts her investigation from the denominations and the location of the bell towers. Patrizia checks whether the sound of those bell towers is done by hand or through electrification. Patrizia checks if there are more or less formalized and more or less recognized groups that carry out those practices. Patrizia verifies, in case of the presence of the groups, what kind of transmission and apprenticeship methods are carried out: in what age groups, if exclusively male or even female, with what type of transmission.

## Competency questions
- Where is the Bell Tower?
- What kind of execution characterizes that bell tower?
- Are there formalized collective actors who carry out sound practices?
- Are there formalized transmission methods that characterize the acquisition of skills related to the bell practice?
- Which age groups do the transmission practices involve?
- Do transmission practices involve both men and women?
- Do transmission practices include the organization of public events?

**Comment by elenamusumeci** [comment]
The story has been added to the repository in [this folder] (https://github.com/polifonia-project/stories/blob/main/Patrizia:ethnoantrhropologist/Patrizia%231_IdentificationOfIntangibleElements.md)
